import type { Metadata } from 'next'
import './globals.css'
import { BackGroundContextProvider } from '@/context/BackgroundContext'


export const metadata: Metadata = {
  title: 'Room homepageApp',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body><BackGroundContextProvider>{children}</BackGroundContextProvider></body>
    </html>
  )
}
